version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql-orcamento
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=oficina_orcamento
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3307:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  api:
    build: .
    container_name: my-fastapi-orcamento
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - USER_DB=lameque
      - PASSWORD_DB=lameque123
      - HOST_DB=db
      - PORT_DB=3307
      - DATABASE=oficina_orcamento
      - SECRET_KEY='fakerandomsecretkey'
      - ALGORITHM=HS256
      - JWT_ISSUER=oficina-auth
      - JWT_AUDIENCE=oficina-api

volumes:
  mysql-volume:
    driver: local