apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: oficina
type: Opaque
stringData:
  USER_DB: "<USER_DB>"
  PASSWORD_DB: "<PASSWORD_DB>"
  HOST_DB: "<HOST_DB>"
  PORT_DB: "<PORT_DB>"
  DATABASE: "<DATABASE>"
  SECRET_KEY: "<SECRET_KEY>"
  ALGORITHM: "<ALGORITHM>"
  JWT_ISSUER: "<JWT_ISSUER>"
  JWT_AUDIENCE: "<JWT_AUDIENCE>"
  URL_API_OS: "<URL_API_OS>"
  MP_ACCESS_TOKEN: "<MP_ACCESS_TOKEN>"
  MP_API: "<MP_API>"
  MP_SUCCESS_URL: "<MP_SUCCESS_URL>"
  MP_FAILURE_URL: "<MP_FAILURE_URL>"
  MP_PENDING_URL: "<MP_PENDING_URL>"
  MP_NOTIFICATION_URL: "<MP_NOTIFICATION_URL>"
