apiVersion: v1
kind: Service
metadata:
  name: oficina-orcamento-api-service
  namespace: oficina
spec:
  type: LoadBalancer
  selector:
    app: oficina-orcamento-api
  ports:
    - port: 8000
      targetPort: 8000
